## Configuration for Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:ms-books-payments}

## Configuration for App name and Spring Data
spring:
  application:
    name: ${APP_NAME:ms-books-payments}
  profiles:
    active:
     DEV
  datasource:
   url: jdbc:h2:mem:testdb;Mode=MySQL
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: create-drop
   defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

management:
 endpoints:
  web:
     exposure:
        include: health,info
## Instance port
server:
  port: ${PORT:8080}

## Configuracion secundaria (custom)
getBook:
 url: http://ms-books-catalogue/books/%s